server:
  port: 81
  ssl:
    key-store: classpath:www.lizhanfeng.xyz.jks
    key-store-password:
    key-store-type: JKS

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://1.15.28.100:3306/poverty_alleviation?useUnicode=true&characterEncoding=utf-8
      username:
      password:

      # 设置最大连接数，默认 100
      max-active: 20
      # 设置最小空闲连接数，默认 8
      min-idle: 5
      # 设置初始化连接数，默认 8
      initial-size: 10
      # 设置访问数据库时，最长等待时间，单位：毫秒，默认 30000
      max-wait: 10000

  redis:
    host: 1.15.28.100
    port: 6379
    password:
    jedis:
      pool:
        # 设置最大连接数，默认 8
        max-active: 32
        # 设置最大空闲连接数，默认8
        max-idle: 16
        # 设置最长等待时间，默认 -1，表示永不超时，时间太长会报连接异常
        max-wait: 300
        # 设置最小空闲连接数
        min-idle: 8
    timeout: 5000
    database: 0

  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1773530070@qq.com
    # 发送者密钥
    password:
    # 发送端口
    port: 25
    # 字符编码
    default-encoding: UTF-8
    # ssl加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
  web:
    resources:
      # 静态资源文件夹
      static-locations: file:D:/00img/static/
  mvc:
    # 访问静态资源文件夹的路径
    static-path-pattern: /static/**

  thymeleaf:
    prefix: D:/00img/static/html/

logging:
  file:
    name: log/warn.log
  level:
    com.inet: warn

path:
  html-path: D:/00img/static/html/
  image-path: D:/00img/static/image/
  video-path: D:/00img/static/video/
  docx-path: D:/00img/static/docx/
  baseUrl: https://localhost:81/
